app/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group( [ 'middleware' => [ 'web' ] ], function () {

	//\Illuminate\Support\Facades\Session::flush();
	//dd(Session::get( 'facebook_access_token' ));

	Route::get( '/', function () {
		return view( 'pages.homepage' );
	} );

	// auth routes
	Route::auth();

	// memories routes
	Route::get( '/memories/facebook-import', 'MemoryController@importFacebook' );
	Route::get( '/memories/instagram-import', 'MemoryController@importInstagram' );
	Route::post( '/memories/upload', 'MemoryController@upload' );

	Route::post( '/memories/filter', 'MemoryController@filter' );
	Route::get( '/memoryfile/{file_name}', 'MemoryController@readFile' );

	Route::resource( 'memories', 'MemoryController' );


	// profile
	Route::get( '/profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit'] );
	Route::put( '/profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update'] );

	// trunk routes
	Route::resource( 'trunks', 'TrunkController' );
    // job routes
    Route::resource('jobs', 'JobController');

	// persons routes
	Route::resource( 'persons', 'PersonController' );

	// sharelinks link routes
	Route::get( 'sharelinks/s/{hash}', 'SharelinkController@hash');
	Route::get( 'sharelinks/read/{file_name}', 'SharelinkController@readFile' );
	Route::resource( 'sharelinks', 'SharelinkController');


} );


/*
|--------------------------------------------------------------------------
| API Endpoints
|--------------------------------------------------------------------------
|
| Endpoints are the similar to routes for an application
|
*/
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['middleware' => 'api.auth'], function ($api) {
	$api->get('users/{user_id}', 'App\Api\V1\Controllers\UserController@show');

	// trunks
	$api->get('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@trunks');
	$api->post('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@store_trunk');
	$api->put('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@update_trunk');



	$api->get('users/{user_id}/memories', 'App\Api\V1\Controllers\UserController@memories');
	$api->get('users/{user_id}/persons', 'App\Api\V1\Controllers\UserController@persons');
	$api->get('users/{user_id}/jobs', 'App\Api\V1\Controllers\UserController@jobs');
});

// not requiring auth
$api->version('v1', function ($api) {
	$api->get('relationships/{relationship_id}', 'App\Api\V1\Controllers\RelationshipController@show');
});

app/app/Models/MemoryType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MemoryType extends Model {

	public $timestamps = false;
}

app/app/Http/Controllers/MemoryController.php
<?php

namespace App\Http\Controllers;

use App\Digix\Memory\FacebookMemory;
use App\Digix\Memory\InstagramMemory;
use App\Http\Requests\MemoryUploadRequest;
use App\Models\Location;
use App\Models\Memory;
use App\Models\Job;
use App\Models\MemoryType;
use App\Models\Person;
use App\Models\RelationshipType;
use App\Models\Sharelink;
use App\Models\Trunk;
use App\Services\MemoryService;
use App\User;
use Facebook\Exceptions\FacebookSDKException;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\View;
use Larabros\Elogram\Exceptions\APINotFoundError;
use Laracasts\Utilities\JavaScript;
use Illuminate\Support\Facades\Config;
use Larabros\Elogram\Exceptions\Exception;


class MemoryController extends Controller {

	private $memory_service;

	public function __construct() {
		$this->middleware( 'auth');
		$this->memory_service = new MemoryService();
	}

	/**
	 * Display a listing of the resource.
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$user     = Auth::user();
		$memories = $this->getAllMemoriesData( $user->id );
		$this->setMemoryBoxClass( $memories );


		$memory_types      = MemoryType::all();
		$jobs              = $user->jobs;
		$trunks            = $user->trunks;
		$persons           = $user->persons;
		$relationships     = RelationshipType::all();
		$locations         = $user->locations;
		$positions         = $user->positions;
		$companies         = $user->companies;
		$memories_ids_json = json_encode( $memories->pluck( 'id' ) );


		return View::make( 'pages.memories.index', [
			'memories'          => $memories,
			'memory_types'      => $memory_types,
			'jobs'              => $jobs,
			'trunks'            => $trunks,
			'persons'           => $persons,
			'relationships'     => $relationships,
			'locations'         => $locations,
			'positions'         => $positions,
			'companies'         => $companies,
			'memories_ids_json' => $memories_ids_json
		] );
	}

	/**
	 * Show the form for creating a new resource.
	 * @return \Illuminate\Http\Response
	 */
	public function create( Request $request ) {
		$user_id   = Auth::id();
		$fb        = new FacebookMemory( $user_id );
		$instagram = new InstagramMemory( $user_id );

		// get social memories if we have them and load them before getting the persons
		$facebook_memories  = Session::pull( 'facebook_memories' );
		$instagram_memories = Session::pull( 'instagram_memories' );
		$memories           = [ ];
		if ( $facebook_memories ) {
			$memories = $facebook_memories;
		} else if ( $instagram_memories ) {
			$memories = $instagram_memories;
		}


		// get user info
		$jobs           = Job::where( 'user_id', $user_id )->get();
		$persons        = Person::where( 'user_id', $user_id )->get();
		$trunks         = Trunk::where( 'user_id', $user_id )->get();
		$facebook_link  = $fb->getImportURL();
		$instagram_link = $instagram->getImportURL();


		return View::make( 'pages.memories.create', array(
			'jobs'           => $jobs,
			'trunks'         => $trunks,
			'persons'        => $persons,
			'facebook_link'  => $facebook_link,
			'instagram_link' => $instagram_link,
			'memories'       => $memories
		) );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {
		// validate
		$this->validate( $request, [
			'title'       => 'required|max:255',
			'file_name'   => 'required_without:source|max:255',
			'source'      => 'required_without:file_name|max:255',
			'trunk_id'    => 'required',
			'type_id'     => 'required',
			'memory_date' => 'required|date_format:d/m/Y'
		] );

		// get logged user and create memory instance
		$memory = new Memory;
		$user   = Auth::user();

		// set either local name or remote source
		if ( $request->file_name ) {
			$memory->file_name = $request->file_name;
		} else {
			$memory->source = $request->source;
		}

		$memory->type_id = $request->type_id;
		$response        = array();

		$memory = $this->checkAndSetAttributes( $memory, $request, $user );
		if ( $memory ) {
			$response = $this->checkAndSetPersons( $memory, $request, $user );
		}

		if ( $memory && $response ) {
			return response()->json( $response );
		} else {
			$response['general']['unknown_error'] = Config::get( 'strings.unknown_error' );

			return response()->json( $response, 422 );
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		$memory = Memory::find( $id );

		return View::make( 'pages.memories.show', [
			'memory' => $memory,
		] );
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		$user    = Auth::user();
		$user_id = $user->id;

		$memory  = Memory::find( $id );
		$jobs    = Job::where( 'user_id', $user_id )->get();
		$persons = Person::where( 'user_id', $user_id )->get();
		$trunks  = Trunk::where( 'user_id', $user_id )->get();

		return View::make( 'pages.memories.edit', [
			'memory'  => $memory,
			'jobs'    => $jobs,
			'trunks'  => $trunks,
			'persons' => $persons,
		] );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		$this->validate( $request, [
			'title'       => 'required|max:255',
			'trunk_id'    => 'required',
			'memory_date' => 'required|date_format:d/m/Y'
		] );

		// get logged user and create memory instance
		$memory   = Memory::find( $id );
		$user     = Auth::user();
		$response = array();

		$memory = $this->checkAndSetAttributes( $memory, $request, $user );
		if ( $memory ) {
			$response = $this->checkAndSetPersons( $memory, $request, $user );
		}

		if ( $memory && $response ) {
			$request->session()->flash( 'flash_message', 'Memory was updated!' );
			$request->session()->flash( 'flash_message_type', 'success' );
		} else {
			$request->session()->flash( 'flash_message', Config::get( 'strings.unknown_error' ) );
			$request->session()->flash( 'flash_message_type', 'error' );
		}

		return Redirect::back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id, Request $request ) {
		$memory   = Memory::find( $id );
		$success  = $memory->delete();
		$response = array();

		if ( $success ) {
			$request->session()->flash( 'flash_message', 'Memory was deleted!' );
			$request->session()->flash( 'flash_message_type', 'success' );
			$response['redirect_url'] = route( 'memories.index' );
		} else {
			$request->session()->flash( 'flash_message', Config::get( 'strings.unknown_error' ) );
			$request->session()->flash( 'flash_message_type', 'error' );
			$response['redirect_url'] = route( 'memories.show', $id );


		}

		return response()->json( $response );
	}


	/**
	 * Filter memories
	 *
	 * @param Request $request
	 */
	public function filter( Request $request ) {
		$response = $this->memory_service->filter( $request->all() );

		if ( ! empty( $response['errors'] ) ) {
			return response()->json( $response['errors'], 422 );
		} else {
			return response()->json( $response['memories_ids'] );
		}
	}

	/**
	 * Used by the plupload script
	 * @todo - store in temp folder, and then delete if the user doesn't complete
	 */
	public function upload( MemoryUploadRequest $request ) {
		$model = new Memory();

		// upload via url from social networks
		if ( $request->url ) {
			$response = $model->upload( $request->url );
		} else {
			$response = $model->upload();
		}

		if ( $response['success'] ) {
			return response()->json( $response );
		} else {
			return response()->json( $response, 422 );
		}
	}

	/**
	 * @return mixed
	 */
	public function importFacebook( Request $request ) {
		$user_id   = Auth::id();
		$fb_memory = new FacebookMemory( $user_id );

		try {
			$memories = $fb_memory->import();

			return redirect()->route( 'memories.create' )->with( 'facebook_memories', $memories );
		} catch( FacebookSDKException $e ) {
			$request->session()->flash( 'flash_message', 'We couldn\'t import from facebook due to the following reason: ' . $e->getMessage() );
			$request->session()->flash( 'flash_message_type', 'error' );

			return redirect()->route( 'memories.create' );
		}
	}

	/**
	 * @return mixed
	 */
	public function importInstagram( Request $request ) {
		$user_id          = Auth::id();
		$instagram_memory = new InstagramMemory( $user_id );

		try {
			$memories = $instagram_memory->import();

			return redirect()->route( 'memories.create' )->with( 'instagram_memories', $memories );
		} catch( Exception  $e ) {
			$request->session()->flash( 'flash_message', 'We couldn\'t import from instragram due to the following reason: ' . $e->getMessage() );
			$request->session()->flash( 'flash_message_type', 'error' );

			return redirect()->route( 'memories.create' );
		}
	}

	/**
	 * @param $memories
	 */
	private function setMemoryBoxClass( $memories ) {
		foreach ( $memories as $memory ) {
			switch ( $memory->type->name ) {
				case 'image':
					$memory->type->class = '';
					break;
				case 'video':
					$memory->type->class = 'fa-file-video-o';
					break;
				case 'document':
					$memory->type->class = 'fa-file-text';
					break;
				case 'audio':
					$memory->type->class = 'fa-file-audio-o';
					break;
				default:
					Log::warning( 'Invalid memory file type.' );
			}
		}
	}

	/**
	 * @param $user_id
	 *
	 * @return \Illuminate\Database\Eloquent\Collection|static[]
	 */
	private function getAllMemoriesData( $user_id ) {
		$memories = Memory::with(
			'trunk',

app/resources/views/pages/memories/create.blade.php
@extends ('layouts.master')

@section('title', 'Add memory - Digi-X')
@section('body-class', 'memories-template create-memory-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Add memory</h1>
    </div>
    <div class="action-bar">
        <div class="container">
            <div class="trunk">
                {{--<label>Trunk:</label>--}}
                {{--<div class="tooltip-select">--}}
                    {{--<select name="trunk">--}}
                        {{--<option>Personal</option>--}}
                        {{--<option>Work</option>--}}
                        {{--<option>Work</option>--}}
                        {{--<option>Work</option>--}}
                        {{--<option>Work</option>--}}
                        {{--<option>Work</option>--}}
                        {{--<option>Work</option>--}}
                    {{--</select>--}}
                {{--</div>--}}
            </div>
            <div class="social">
                <span>Add with:</span>
                <ul>
                    <li><a href="#" data-toggle="modal" data-target="#import-facebook-memory">Facebook</a></li>
                    <li><a href="#" data-toggle="modal" data-target="#import-instagram-memory">Instagram</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="drag-drop-section">
        <div class="container">
            <p class="intro">You can add <a href="{{ url('persons/create') }}">persons</a>, <a href="{{ url('jobs/create') }}">jobs</a> and <a href="{{ url('trunks/create') }}">trunks</a> for a better use of the filters. Allowed filetypes: png, jpeg, jpg, mp4, qt, mov, avi, txt, pdf, doc, docx, ppt, pptx, xls, xml, rtf, mp3, wav, midi. </p>

            <div id="drag-drop-area" style="position: relative;">
                <div class="drag-drop-inside">
                    <div class="cloud-upload-container">
                        <i id="plupload-browse-button" class="fa fa-icon fa-cloud-upload "></i>
                    </div>
                </div>
            </div>
            <div id="files-list">
                @if($memories)
                    @foreach($memories as $memory)
                        <div class="file" id="{{ $memory->social_html_id }}" data-prepopulate="{{ json_encode($memory) }}">
                            <span class="type">{{ $memory->type_name }}</span>
                            <span class="name">{{ $memory->title }}</span>
                            <span class="size">
                                @if($memory->social_type == 'facebook')
                                    <i class="fa fa-facebook-official"></i>
                                @elseif($memory->social_type == 'instagram')
                                    <i class="fa fa-instagram"></i>
                                @endif
                                @if($memory->notes)<b>{{ $memory->notes }}</b>@endif
                            </span>
                            <span class="status">
                                <span class="message">
                                    <a href="#" class="upload-by-url">Upload</a>
                                    <a href="{{ $memory->source }}" target="_blank" class="see-asset">See</a>
                                    <a href="#" class="remove">Remove</a>
                                </span>
                                <div class="progress-bar"><div class="helper"></div></div>
                            </span>
                        </div>
                    @endforeach
                @endif
            </div>
            <!--a id="upload-files" class="button" href="#">Upload memories</a-->
        </div>
    </div>
    <div class="modal fade" id="edit-memory" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2>Quick edit</h2>
                </div>
                <form method="POST" action="{{ action('MemoryController@store') }}">
                    {!! csrf_field() !!}
                    <div class="modal-body">
                        <div class="form-field">
                            <label>Title</label>
                            <input type="text" name="title" value="">
                        </div>
                        <div class="form-field">
                            <label>Description</label>
                            <textarea name="description"></textarea>
                        </div>
                        <div class="form-field">
                            <label>Trunk</label>
                            <select name="trunk_id">
                                @foreach($trunks as $trunk)
                                    <option value="{{ $trunk->id }}">{{ $trunk->title }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-field">
                            <label>Persons in memory</label>
                            <select name="persons[]" class="selectize" multiple>
                                @foreach($persons as $person)
                                    <option value="{{ $person->id }}">{{ $person->display_name() }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-field">
                            <label>Location</label>
                            <input class="location" name="location_name" type="text" value="">
                            <input type="hidden" name="location_data" value="">
                        </div>
                        <div class="form-field">
                            <label>Job</label>
                            <select name="job_id">
                                <option value="0">No job</option>
                                @foreach($jobs as $job)
                                    <option value="{{ $job->id }}">{{ $job->position->title }}, {{ $job->company->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-field">
                            <label>Date</label>
                            <input name="memory_date" type='text' class="datepicker" />
                        </div>
                        <input type="hidden" name="type_id" value="">
                        <input type="hidden" name="file_name" value="">
                        <input type="hidden" name="source" value="">
                        <input type="hidden" name="fb_id" value="">
                        <input type="hidden" name="instagram_id" value="">
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="full-width">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="import-facebook-memory" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2>Facebook memories</h2>
                </div>
                <div class="modal-body">
                    <p>Importing your videos and photos from facebook. All persons tagged will get created in DIGI-X. Import?</p>
                </div>
                <div class="modal-footer">
                    <a href="{{ $facebook_link }}" class="social-link-import button">Import</a>
                    <button type="button" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="import-instagram-memory" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2>Instagram memories</h2>
                </div>
                <div class="modal-body">
                    <p>Importing your videos and photos from instagram. All persons tagged will get created in DIGI-X. Import?</p>
                </div>
                <div class="modal-footer">
                    <a href="{{ $instagram_link }}" class="social-link-import button">Import</a>
                    <button type="button" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
@endsection

app/resources/views/pages/memories/edit.blade.php
    @extends ('layouts.master')

@section('title', 'Edit memory - Digi-X')
@section('body-class', 'memories-template  edit-memory-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Edit memory</h1>
    </div>
    <div class="edit-memory section form-section">
        <div class="container">
            <form method="POST" action="{{ action('MemoryController@update', $memory->id) }}">
                <input type="hidden" name="_method" value="PUT">
                {!! csrf_field() !!}
                <div class="modal-body">
                    <div class="form-field">
                        <label>Title</label>
                        <input type="text" name="title" value="{{ $memory->title }}">
                        {!! d_error('title', $errors->toArray()) !!}
                    </div>
                    <div class="form-field">
                        <label>Description</label>
                        <textarea name="description">{{ $memory->description }}</textarea>
                        {!! d_error('description', $errors->toArray()) !!}
                    </div>
                    <div class="form-field">
                        <label>Trunk</label>
                        <select name="trunk_id">
                            @foreach($trunks as $trunk)
                                <option value="{{ $trunk->id }}" @if($trunk->id == $memory->trunk_id) selected @endif>{{ $trunk->title }}</option>
                            @endforeach
                        </select>
                        {!! d_error('trunk_id', $errors->toArray()) !!}
                    </div>
                    <div class="form-field">
                        <label>Persons in memory</label>
                        <select name="persons[]" class="selectize" multiple>
                            @foreach($persons as $person)
                                <option value="{{ $person->id }}" @if($memory->persons->contains($person->id)) selected @endif>{{ $person->display_name() }}</option>
                            @endforeach
                        </select>
                        {!! d_error('persons', $errors->toArray()) !!}
                    </div>
                    <div class="form-field">
                        <label for="password">Location</label>
                        <input class="location" name="location_name" type="text" value="{{ $memory->location->name }}">
                        <input type="hidden" name="location_data" value="">
                        {!! d_error('location', $errors->toArray()) !!}
                    </div>
                    <div class="form-field">
                        <label>Job</label>
                        <select name="job_id">
                            <option value="0">No job</option>
                            @foreach($jobs as $job)
                                <option value="{{ $job->id }}"  @if($job->id == $memory->job_id) selected @endif>{{ $job->position->title }}, {{ $job->company->name }}</option>
                            @endforeach
                        </select>
                        {!! d_error('job_id', $errors->toArray()) !!}
                    </div>
                    <div class="form-field">
                        <label>Date</label>
                        <input name="memory_date" type='text' class="datepicker" value="{{ $memory->memory_date->format('d/m/Y') }}"/>
                        {!! d_error('memory_date', $errors->toArray()) !!}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="full-width">Save changes</button>
                </div>
            </form>
        </div>
    </div>
@endsection

app/resources/views/pages/memories/show.blade.php
@extends ('layouts.master')

@section('title', 'Memory - Digi-X')
@section('body-class', 'memories-template  show-memory-template')

@section('content')
    <div class="memory-file-cont type-{{ $memory->type->name }}">
        <div class="overlay"></div>
        <div class="vertical-align-helper"></div>
        @if($memory->type->name == 'image')
        <img class="memory-file"
             src="@if($memory->file_name){{url('memoryfile/' . $memory->id ) }}@else{{ $memory->source }}@endif"
             alt="#">
        @elseif($memory->type->name == 'video')
            <div class="video-wrapper">
                <video class="video-js vjs-default-skin vjs-big-play-centered memory-file" controls
                       preload="auto"
                       data-setup='{}'>
                    <source src="@if($memory->file_name){{url('memoryfile/' . $memory->id ) }}@else{{ $memory->source }}@endif" type="video/{{ $memory->ext() }}">
                    <p class="vjs-no-js">
                        To view this video please enable JavaScript, and consider upgrading to a web browser
                        that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                    </p>
                </video>
            </div>
        @else
            <a class="memory-file icon" href="@if($memory->file_name){{url('memoryfile/' . $memory->id ) }}@else{{ $memory->source }}@endif" target="_blank">
                <i class="fa fa-cloud-download"></i>
            </a>
        @endif
    </div>
    <div class="show-memory section form-section">
        <div class="container">
            <div class="title">
                <h2>{{ $memory->title }}</h2>
            </div>
            <span class="date">
                <i class="fa fa-calendar-o"></i>
                {{ $memory->memory_date->diffForHumans() }}
            </span>
            <div class="content">
                <p>
                    {{ $memory->description }} -
                    @if ($memory->location)
                        <span><b>at</b> {{ $memory->location->name }}</span>
                    @endif
                    @if (!$memory->persons->isEmpty())
                        <span><b>with</b>
                            @foreach($memory->persons as $key => $person)
                                @if($key != 0),@endif
                                <a href="{{ route('persons.edit', $person->id) }}">{{ $person->display_name() }}</a>
                            @endforeach
                        </span>
                    @endif
                    @if ($memory->trunk)
                        <span><b>in</b> <a href="{{ route('trunks.edit', $memory->trunk->id) }}">{{ $memory->trunk->title }}</a></span>
                    @endif
                </p>
            </div>
            <div class="actions">
                <a href="{{ route('memories.edit', $memory->id) }}" class="button">Edit memory</a>
                <a href="{{ route('memories.destroy', $memory->id) }}" class="button delete-memory" data-id="{{ $memory->id }}" data-token="{{ csrf_token() }}">Delete memory</a>
            </div>
        </div>
    </div>
@endsection