app/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group( [ 'middleware' => [ 'web' ] ], function () {

	//\Illuminate\Support\Facades\Session::flush();
	//dd(Session::get( 'facebook_access_token' ));

	Route::get( '/', function () {
		return view( 'pages.homepage' );
	} );

	// auth routes
	Route::auth();

	// memories routes
	Route::get( '/memories/facebook-import', 'MemoryController@importFacebook' );
	Route::get( '/memories/instagram-import', 'MemoryController@importInstagram' );
	Route::post( '/memories/upload', 'MemoryController@upload' );

	Route::post( '/memories/filter', 'MemoryController@filter' );
	Route::get( '/memoryfile/{file_name}', 'MemoryController@readFile' );

	Route::resource( 'memories', 'MemoryController' );


	// profile
	Route::get( '/profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit'] );
	Route::put( '/profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update'] );

	// trunk routes
	Route::resource( 'trunks', 'TrunkController' );
    // job routes
    Route::resource('jobs', 'JobController');

	// persons routes
	Route::resource( 'persons', 'PersonController' );

	// sharelinks link routes
	Route::get( 'sharelinks/s/{hash}', 'SharelinkController@hash');
	Route::get( 'sharelinks/read/{file_name}', 'SharelinkController@readFile' );
	Route::resource( 'sharelinks', 'SharelinkController');


} );


/*
|--------------------------------------------------------------------------
| API Endpoints
|--------------------------------------------------------------------------
|
| Endpoints are the similar to routes for an application
|
*/
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['middleware' => 'api.auth'], function ($api) {
	$api->get('users/{user_id}', 'App\Api\V1\Controllers\UserController@show');

	// trunks
	$api->get('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@trunks');
	$api->post('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@store_trunk');
	$api->put('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@update_trunk');



	$api->get('users/{user_id}/memories', 'App\Api\V1\Controllers\UserController@memories');
	$api->get('users/{user_id}/persons', 'App\Api\V1\Controllers\UserController@persons');
	$api->get('users/{user_id}/jobs', 'App\Api\V1\Controllers\UserController@jobs');
});

// not requiring auth
$api->version('v1', function ($api) {
	$api->get('relationships/{relationship_id}', 'App\Api\V1\Controllers\RelationshipController@show');
});

app/app/Models/Sharelink.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sharelink extends Model
{
    /**
     * Returns user
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(){
        return $this->belongsTo('App\User');
    }

    /**
     * Return memory
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function memory(){
        return $this->belongsTo('App\Models\Memory');
    }
}

app/app/Http/Controllers/SharelinkController.php
<?php

namespace App\Http\Controllers;

use App\Events\ShareLinkAccessed;
use App\Models\Memory;
use App\Models\Sharelink;
use Illuminate\Http\Request;
use Carbon\Carbon;

use App\Http\Requests;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Auth;

class SharelinkController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['hash', 'readFile']]);

    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::id();
        $sharelinks = Sharelink::where('user_id', $user_id)->get();

        return View::make('pages.sharelinks.index', compact('sharelinks'));
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $user_id = Auth::id();
        $memories = Memory::where('user_id', $user_id)->get();

        return View::make('pages.sharelinks.create', compact('memories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user_id = Auth::id();

        $this->validate($request, [
            'memory_id' => 'required',
        ]);

        $sharelink = new Sharelink();
        $sharelink->memory_id = $request->memory_id;

        $sharelink->user_id = $user_id;

        $string = $user_id . $request->memory_id . uniqid();

        $hashed_link = md5($string);

        $sharelink->hashed_link = $hashed_link;

        $saved = $sharelink->save();

        if ($saved) {
            $request->session()->flash('flash_message', 'Sharelink was created!');
            $request->session()->flash('flash_message_type', 'success');
        } else {
            $request->session()->flash('flash_message', Config::get('strings.unknown_error'));
            $request->session()->flash('flash_message_type', 'error');
        }

        return Redirect::back();
    }

    public function hash($hash)
    {
        $sharelink = Sharelink::where('hashed_link', $hash)->first();

        if ($sharelink) {
            $generated_at = $sharelink->created_at;
            $alive_link_time = $generated_at->addDay(1);
            $time_right_now = Carbon::now();
            $time_passed = $time_right_now->diffInSeconds($alive_link_time);

            if ($time_passed > 86400) {
                return Response::make(null, 410);
            }

            Event::fire(new ShareLinkAccessed($sharelink));

            return View::make( 'pages.sharelinks.show', [
                'memory' => $sharelink->memory,
                'hash' => $sharelink->hashed_link,
            ] );
        } else {
            return Response::make(null, 404); //should be 404 or custom not 403
        }
    }

    public function destroy($id)
    {

        $sharelink = Sharelink::where('id', $id);
        $sharelink->delete();

        return Redirect::back();
    }

    /**
     * Reads file from folder outside root
     * @param $hash
     *
     * @return mixed
     */
    public function readFile( $hash ) {
        $sharelink = Sharelink::where('hashed_link', $hash)->first();
        $memory = $sharelink->memory;

        $file_path = $memory->get_file_path( $memory->file_name, $memory->user_id);

        $file = $file_path;
        if ( file_exists( $file ) ) {
            $finfo = finfo_open( FILEINFO_MIME_TYPE );
            $mime  = finfo_file( $finfo, $file );
            finfo_close( $finfo );
            header( "Content-Type: $mime" );
            readfile( $file );
        } else {
            return Response::make( null, 403 );
        }
    }

}

app/resources/views/pages/sharelinks/create.blade.php
@extends ('layouts.master')

@section('title', 'Add sharelink - Digi-X')
@section('body-class', 'persons create-person-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Add sharelink</h1>
    </div>
    <div class="create-person section form-section">
        <div class="container">
            <form method="POST" action="{{ action('SharelinkController@store') }}">
                {!! csrf_field() !!}
                @if( !($memories->isEmpty() ) )
                    <div class="form-field">
                        <label>Memory name</label>
                        <select name="memory_id">
                            @foreach ($memories as $memory)
                                <option value="{{ $memory->id }}"
                                        @if($memory->id == old('memory_id')) selected
                                        @endif
                                >{{ $memory->title }}</option>
                            @endforeach
                        </select>
                        {!! d_error('memory_id', $errors->toArray()) !!}
                    </div>

                <button type="submit" class="full-width">Add sharelink</button>
                @else
                    <p class="no-resource">You have no memories to create sharelinks, get started <a
                                href="{{ route('memories.create') }}">here</a>.</p>
                @endif
            </form>
        </div>
    </div>
@endsection

app/resources/views/pages/sharelinks/index.blade.php
@extends ('layouts.master')

@section('title', 'Listing sharelinks - Digi-X')
@section('body-class', 'trunks edit-trunk-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Your sharelinks</h1>
        <a href="{{ route('sharelinks.create') }}" class="button add">
            <i class="fa fa-plus"></i>
        </a>
    </div>
    <div class="trunks-listing section listing-section">
        <div class="container small">
            @if ($sharelinks)
                @if( !($sharelinks->isEmpty() ) )
                    <div class="table">
                        <div class="head row resp-table">
                            <div class="cell">Memory name</div>
                            <div class="cell">Sharelink</div>
                            <div class="cell">&nbsp;</div>
                        </div>
                        @foreach($sharelinks as $sharelink)
                            <div class="row">
                                <div class="cell">{{ str_limit($sharelink->memory->title, $limit = 20, $end = '...') }}</div>
                                <div class="cell">{{ url('/sharelinks/s/' . str_limit($sharelink->hashed_link, $limit = 10, $end = '...')) }}</div>
                                <div class="cell actions">
                                    <a href="javascript: return false;" class="clipbrd" title="Copied!" data-clipboard-text="{{ url('/sharelinks/s/' . $sharelink->hashed_link) }}"><i class="fa fa-copy"></i>Copy</a>
                                    <!--a href=""><i class="fa fa-trash"></i>Delete</a-->
                                </div>
                            </div>
                        @endforeach
                    </div>
                @else
                    <p class="no-resource">You haven't added any share links yet, get started <a href="{{ route('sharelinks.create') }}">here</a>.</p>
                @endif
            @endif
        </div>
    </div>
@endsection

app/resources/views/pages/sharelinks/show.blade.php
@extends ('layouts.master')

@section('title', 'Memory - Digi-X')
@section('body-class', 'memories-template  show-memory-template')

@section('content')
    <div class="memory-file-cont type-{{ $memory->type->name }}">
        <div class="overlay"></div>
        <div class="vertical-align-helper"></div>
        @if($memory->type->name == 'image')
            <img class="memory-file"src="@if($memory->file_name){{url('sharelinks/read/' . $hash ) }}@else {{ $memory->source }} @endif" alt="#">
        @endif
    </div>
    <div class="show-memory section form-section">
        <div class="container">
            <div class="title">
                <h2>{{ $memory->title }}</h2>
            </div>
            <span class="date">
                <i class="fa fa-calendar-o"></i>
                {{ $memory->memory_date->diffForHumans() }}
            </span>
            <div class="content">
                <p>
                    {{ $memory->description }} -
                    @if ($memory->location)
                        <span><b>at</b> {{ $memory->location->name }}</span>
                    @endif
                    @if (!$memory->persons->isEmpty())
                        <span><b>with</b>
                            @foreach($memory->persons as $key => $person)
                                @if($key != 0),@endif
                                <a href="{{ route('persons.edit', $person->id) }}">{{ $person->display_name() }}</a>
                            @endforeach
                        </span>
                    @endif
                    @if ($memory->trunk)
                        <span><b>in</b> <a href="{{ route('trunks.edit', $memory->trunk->id) }}">{{ $memory->trunk->title }}</a></span>
                    @endif
                </p>
            </div>
        </div>
    </div>
@endsection