app/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group( [ 'middleware' => [ 'web' ] ], function () {

	//\Illuminate\Support\Facades\Session::flush();
	//dd(Session::get( 'facebook_access_token' ));

	Route::get( '/', function () {
		return view( 'pages.homepage' );
	} );

	// auth routes
	Route::auth();

	// memories routes
	Route::get( '/memories/facebook-import', 'MemoryController@importFacebook' );
	Route::get( '/memories/instagram-import', 'MemoryController@importInstagram' );
	Route::post( '/memories/upload', 'MemoryController@upload' );

	Route::post( '/memories/filter', 'MemoryController@filter' );
	Route::get( '/memoryfile/{file_name}', 'MemoryController@readFile' );

	Route::resource( 'memories', 'MemoryController' );


	// profile
	Route::get( '/profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit'] );
	Route::put( '/profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update'] );

	// trunk routes
	Route::resource( 'trunks', 'TrunkController' );
    // job routes
    Route::resource('jobs', 'JobController');

	// persons routes
	Route::resource( 'persons', 'PersonController' );

	// sharelinks link routes
	Route::get( 'sharelinks/s/{hash}', 'SharelinkController@hash');
	Route::get( 'sharelinks/read/{file_name}', 'SharelinkController@readFile' );
	Route::resource( 'sharelinks', 'SharelinkController');


} );


/*
|--------------------------------------------------------------------------
| API Endpoints
|--------------------------------------------------------------------------
|
| Endpoints are the similar to routes for an application
|
*/
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['middleware' => 'api.auth'], function ($api) {
	$api->get('users/{user_id}', 'App\Api\V1\Controllers\UserController@show');

	// trunks
	$api->get('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@trunks');
	$api->post('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@store_trunk');
	$api->put('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@update_trunk');



	$api->get('users/{user_id}/memories', 'App\Api\V1\Controllers\UserController@memories');
	$api->get('users/{user_id}/persons', 'App\Api\V1\Controllers\UserController@persons');
	$api->get('users/{user_id}/jobs', 'App\Api\V1\Controllers\UserController@jobs');
});

// not requiring auth
$api->version('v1', function ($api) {
	$api->get('relationships/{relationship_id}', 'App\Api\V1\Controllers\RelationshipController@show');
});

app/resources/views/includes/footer.blade.php
<footer>
    <p class="copyright">Copyright © 2016 - Orzu Ionut, Bunea Daniel, Calara Cristian</p>
</footer>
@if (Session::has('flash_message'))
    <div class="flash-notification {{ Session::get('flash_message_type') }}">
        <div class="container">
            <div class="messages">
                <span>{{ Session::get('flash_message') }}</span>
            </div>
            <button type="button" class="close" ><span aria-hidden="true">×</span></button>
        </div>
    </div>
@else
    <div class="flash-notification">
        <div class="container">
            <div class="messages"></div>
            <button type="button" class="close" ><span aria-hidden="true">×</span></button>
        </div>
    </div>
@endif

app/resources/views/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Digi-X - @yield('title')</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href='{{ URL::asset('css/vendor/formstone/checkbox.css') }}' rel='stylesheet' type='text/css'>
<link href='{{ URL::asset('css/vendor/formstone/scrollbar.css') }}' rel='stylesheet' type='text/css'>
<link href='{{ URL::asset('css/vendor/formstone/dropdown.css') }}' rel='stylesheet' type='text/css'>
<link href="http://vjs.zencdn.net/5.10.2/video-js.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{{ URL::asset('css/vendor/font-awesome/css/font-awesome.min.css') }}" />
<link rel="stylesheet" href="{{ URL::asset('css/app.css') }}" />
<link rel="stylesheet" href="{{ URL::asset('css/tooltipster.css') }}" />

app/resources/views/includes/header.blade.php
<header>
    <div class="container">
        <div class="logo">
            <h1><a href="{{ url('/')  }}">Digi-X</a></h1>
        </div>
        <div class="menu">
            <ul>
                @if(!Auth::check())
                    <li><a href="{{ url('login') }}">Login</a></li>
                    <li><a href="{{ url('register') }}">Register</a></li>
                @else
                    <li><a href="{{ route('memories.index') }}">Memories</a></li>
                    <li><a href="{{ route('trunks.index') }}">Trunks</a></li>
                    <li><a href="{{ route('jobs.index') }}">Jobs</a></li>
                    <li><a href="{{ route('persons.index') }}">Persons</a></li>
                    <li><a href="{{ route('sharelinks.index') }}">Sharelinks</a></li>
                    <li><a href="{{ route('profile.edit') }}">Profile</a></li>
                    <li><a href="{{ url('logout') }}">Logout</a></li>
                @endif
            </ul>
        </div>
    </div>
</header>

app/resources/views/includes/scripts.blade.php
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>


<!-- formstone -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/formstone/core.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/vendor/formstone/checkbox.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/vendor/formstone/scrollbar.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/vendor/formstone/touch.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/vendor/formstone/dropdown.js') }}'></script>



<!-- video js -->
<script src="http://vjs.zencdn.net/5.10.2/video.js"></script>


<!-- modal -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/bootstrap.js') }}'></script>
<!-- datepicker -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/moment.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/vendor/bootstrap-datetimepicker.js') }}'></script>
<!-- selectize -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/selectize.js') }}'></script>

<!-- utils -->
<script type='text/javascript' src='{{ URL::asset('js/jquery.digix-utils.js') }}'></script>


<!-- location field -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script type='text/javascript' src='{{ URL::asset('js/vendor/typehead.bundle.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/jquery.digix-location.js') }}'></script>

<!-- memories -->
<script type='text/javascript' src='{{ URL::asset('js/pages/memories.js') }}'></script>

<!-- memories.index -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/jquery.mixitup.min.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/jquery.digix-filters.js') }}'></script>

<!-- memories.create -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/plupload/plupload.full.min.js') }}'></script>
<!-- debug
<script type="text/javascript" src="../js/moxie.js"></script>
<script type="text/javascript" src="../js/plupload.dev.js"></script>
-->
<script type='text/javascript' src='{{ URL::asset('js/jquery.digix-upload.js') }}'></script>


<!-- jobs.add -->
<script type='text/javascript' src='{{ URL::asset('js/pages/jobs.js') }}'></script>
<!-- persons.add -->
<script type='text/javascript' src='{{ URL::asset('js/pages/persons.js') }}'></script>

<script type='text/javascript' src='{{ URL::asset('js/jquery.script.js') }}'></script>

<!-- copy to clipboard -->
<script type='text/javascript' src='{{ URL::asset('js/vendor/clipboard.min.js') }}'></script>

<script type='text/javascript' src='{{ URL::asset('js/jquery.tooltipster.min.js') }}'></script>
<script type='text/javascript' src='{{ URL::asset('js/js.clipboard.js') }}'></script>