app/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group( [ 'middleware' => [ 'web' ] ], function () {

	//\Illuminate\Support\Facades\Session::flush();
	//dd(Session::get( 'facebook_access_token' ));

	Route::get( '/', function () {
		return view( 'pages.homepage' );
	} );

	// auth routes
	Route::auth();

	// memories routes
	Route::get( '/memories/facebook-import', 'MemoryController@importFacebook' );
	Route::get( '/memories/instagram-import', 'MemoryController@importInstagram' );
	Route::post( '/memories/upload', 'MemoryController@upload' );

	Route::post( '/memories/filter', 'MemoryController@filter' );
	Route::get( '/memoryfile/{file_name}', 'MemoryController@readFile' );

	Route::resource( 'memories', 'MemoryController' );


	// profile
	Route::get( '/profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit'] );
	Route::put( '/profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update'] );

	// trunk routes
	Route::resource( 'trunks', 'TrunkController' );
    // job routes
    Route::resource('jobs', 'JobController');

	// persons routes
	Route::resource( 'persons', 'PersonController' );

	// sharelinks link routes
	Route::get( 'sharelinks/s/{hash}', 'SharelinkController@hash');
	Route::get( 'sharelinks/read/{file_name}', 'SharelinkController@readFile' );
	Route::resource( 'sharelinks', 'SharelinkController');


} );


/*
|--------------------------------------------------------------------------
| API Endpoints
|--------------------------------------------------------------------------
|
| Endpoints are the similar to routes for an application
|
*/
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['middleware' => 'api.auth'], function ($api) {
	$api->get('users/{user_id}', 'App\Api\V1\Controllers\UserController@show');

	// trunks
	$api->get('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@trunks');
	$api->post('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@store_trunk');
	$api->put('users/{user_id}/trunks', 'App\Api\V1\Controllers\UserController@update_trunk');



	$api->get('users/{user_id}/memories', 'App\Api\V1\Controllers\UserController@memories');
	$api->get('users/{user_id}/persons', 'App\Api\V1\Controllers\UserController@persons');
	$api->get('users/{user_id}/jobs', 'App\Api\V1\Controllers\UserController@jobs');
});

// not requiring auth
$api->version('v1', function ($api) {
	$api->get('relationships/{relationship_id}', 'App\Api\V1\Controllers\RelationshipController@show');
});

app/app/Models/Person.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Person extends Model {

	/**
	 * The table associated with the model.
	 * @var string
	 */
	protected $table = 'persons';

	protected $dates = [ 'created_at', 'updated_at', 'date_of_birth' ];


	/**
	 * @param $date
	 */
	public function setDateOfBirthAttribute( $date ) {
		$this->attributes['date_of_birth'] = Carbon::createFromFormat('d/m/Y', $date);
	}

	/**
	 * Display a person name
	 * @return string
	 */
	public function display_name() {
		return $this->first_name . ' ' . $this->last_name;
	}


	/**
	 * The memories that have this person tagged
	 */
	public function memories() {
		return $this->belongsToMany( 'App\Models\Memory' );
	}

	public function relationshiptypes(){
		return $this->hasOne('App\Models\RelationshipType', 'id', 'relationship_id');
	}

}

app/app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Models\RelationshipType;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use View;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Config;

use App\Models\Person;

class PersonController extends Controller {

	public function __construct() {
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$user_id = Auth::id();
		$persons = Person::where('user_id', $user_id)->get();
		
		return View::make( 'pages.persons.index', compact('persons'));
	}

	/**
	 * Show the form for creating a new resource.
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		$relationships = RelationshipType::all();

		return View::make( 'pages.persons.create', [
			'relationships' => $relationships
		] );
	}

	/**
	 * Store a newly created resource in storage.
	 * @todo - check if relationship_id is valid
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {
		$user_id = Auth::id();

		$this->validate( $request, [
			'first_name'      => 'required|string',
			'last_name'       => 'required|string',
			'relationship_id' => 'required|integer'
		] );

		$person = new Person;
		$person->user_id = $user_id;
		$person->first_name = $request->first_name;
		$person->last_name = $request->last_name;
		$person->relationship_id = $request->relationship_id;
		if($request->date_of_birth){
			$person->date_of_birth = $request->date_of_birth;
		}
		$saved = $person->save();

		if($saved){
			$request->session()->flash('flash_message', 'Person was added!');
			$request->session()->flash('flash_message_type', 'success');
			//$response['redirect_url'] = action('PersonController@create');
			//return response()->json( $response );
		} else {
			$request->session()->flash('flash_message', Config::get('strings.unknown_error'));
			$request->session()->flash('flash_message_type', 'error');
		}

		return Redirect::back();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show() {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		$person = Person::find($id);
		$relationships = RelationshipType::all();

		return View::make( 'pages.persons.edit', [
				'person' => $person,
				'relationships' => $relationships
		] );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		$this->validate( $request, [
				'first_name'      => 'required|string',
				'last_name'       => 'required|string',
				'relationship_id' => 'required|integer'
		] );

		$user = Auth::user();
		if(!$user->is_person_owner($id)){
			$request->session()->flash('flash_message', Config::get('strings.unknown_error'));
			$request->session()->flash('flash_message_type', 'error');
			return Redirect::back();
		};

		$person = Person::find($id);
		$person->first_name = $request->first_name;
		$person->last_name = $request->last_name;
		$person->relationship_id = $request->relationship_id;
		if($request->date_of_birth){
			$person->date_of_birth = $request->date_of_birth;
		}
		$saved = $person->save();

		if($saved){
			$request->session()->flash('flash_message', 'Person was updated!');
			$request->session()->flash('flash_message_type', 'success');
		} else {
			$request->session()->flash('flash_message', Config::get('strings.unknown_error'));
			$request->session()->flash('flash_message_type', 'error');
		}

//		return Redirect::back();
		return redirect('/persons');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		$person = Person::find($id);

		$destroyed = $person->delete();

		return redirect('/persons');
	}
}

app/resources/views/pages/persons/_form.blade.php
{!! csrf_field() !!}
<div class="form-field">
    <label>First name</label>
    <input type="text" name="first_name" value="{{ old('first_name') }}">
    {!! d_error('first_name', $errors->toArray()) !!}
</div>
<div class="form-field">
    <label>Last name</label>
    <input type="text" name="last_name" value="{{ old('last_name') }}">
    {!! d_error('last_name', $errors->toArray()) !!}
</div>
<div class="form-field">
    <label>Date of birth</label>
    <input type="text" class="datepicker" name="date_of_birth" value="{{ old('date_of_birth') }}">
    {!! d_error('date_of_birth', $errors->toArray()) !!}
</div>
<div class="form-field">
    <label>Relationship</label>
    <select name="relationship_id">
        @foreach ($relationships as $relationship)
            <option value="{{ $relationship->id }}"
                    @if($relationship->id == old('relationship_id')) selected
                    @endif
            >{{ $relationship->name }}</option>
        @endforeach
    </select>
    {!! d_error('relationship_id', $errors->toArray()) !!}
</div>
<button type="submit" class="full-width">{{ $submitButtonText }}</button>

app/resources/views/pages/persons/create.blade.php
@extends ('layouts.master')

@section('title', 'Add person - Digi-X')
@section('body-class', 'persons create-person-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Add person</h1>
    </div>
    <div class="create-person section form-section">
        <div class="container">
            <form method="POST" action="{{ action('PersonController@store') }}">
                {!! csrf_field() !!}
                <div class="form-field">
                    <label>First name</label>
                    <input type="text" name="first_name" value="{{ old('first_name') }}">
                    {!! d_error('first_name', $errors->toArray()) !!}
                </div>
                <div class="form-field">
                    <label>Last name</label>
                    <input type="text" name="last_name" value="{{ old('last_name') }}">
                    {!! d_error('last_name', $errors->toArray()) !!}
                </div>
                <div class="form-field">
                    <label>Date of birth</label>
                    <input type="text" class="datepicker" name="date_of_birth" value="{{ old('date_of_birth') }}">
                    {!! d_error('date_of_birth', $errors->toArray()) !!}
                </div>
                <div class="form-field">
                    <label>Relationship</label>
                    <select name="relationship_id">
                        @foreach ($relationships as $relationship)
                            <option value="{{ $relationship->id }}"
                                @if($relationship->id == old('relationship_id')) selected
                                @endif
                            >{{ $relationship->name }}</option>
                        @endforeach
                    </select>
                    {!! d_error('relationship_id', $errors->toArray()) !!}
                </div>
                <button type="submit" class="full-width">Add person</button>
            </form>
        </div>
    </div>
@endsection

app/resources/views/pages/persons/edit.blade.php
@extends ('layouts.master')

@section('title', 'Edit person - Digi-X')
@section('body-class', 'persons edit-person-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Edit person</h1>
    </div>
    <div class="add-person section form-section">
        <div class="container">
            <form method="POST" action="{{ action('PersonController@update', $person->id) }}">
                <input type="hidden" name="_method" value="PUT">
                {!! csrf_field() !!}
                <div class="form-field">
                    <label>First name</label>
                    <input type="text" name="first_name" value="{{ $person->first_name }}">
                    {!! d_error('first_name', $errors->toArray()) !!}
                </div>
                <div class="form-field">
                    <label>Last name</label>
                    <input type="text" name="last_name" value="{{ $person->last_name }}">
                    {!! d_error('last_name', $errors->toArray()) !!}
                </div>
                <div class="form-field">
                    <label>Date of birth</label>
                    <input type="text" class="datepicker" name="date_of_birth" value="@if($person->date_of_birth){{ $person->date_of_birth->format('Y/m/d')  }}@endif">
                    {!! d_error('date_of_birth', $errors->toArray()) !!}
                </div>
                <div class="form-field">
                    <label>Relationship</label>
                    <select name="relationship_id">
                        @foreach ($relationships as $relationship)
                            <option value="{{ $relationship->id }}"
                                    @if($relationship->id == $person->relationship_id) selected
                                    @endif>{{ $relationship->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="full-width">Save info</button>
            </form>
        </div>
    </div>
@endsection

app/resources/views/pages/persons/index.blade.php
@extends ('layouts.master')

@section('title', 'Listing jobs - Digi-X')
@section('body-class', 'jobs edit-job-template')

@section('content')
    <div class="page-title with-image">
        <div class="overlay"></div>
        <h1>Your persons</h1>
        <input class="table-filter" type="text" name="person_filter" placeholder="Search">
        <a href="{{ route('persons.create') }}" class="button add">
            <i class="fa fa-plus"></i>
        </a>
    </div>
    <div class="jobs-listing section listing-section">
        <div class="container small">
            @if ($persons)
                @if( !($persons->isEmpty() ) )
                    <div class="table table-filter resp-table">
                        <div class="head row">
                            <div class="cell">First name</div>
                            <div class="cell">Last name</div>
                            <div class="cell">Relationship</div>
                            <div class="cell">Date of birth</div>
                            <div class="cell">&nbsp;</div>
                        </div>

                        @foreach($persons as $person)
                            <div class="row">
                                <div class="cell filter-cell">{{ str_limit($person->first_name, $limit = 20, $end = '...') }}</div>
                                <div class="cell filter-cell">{{ str_limit($person->last_name, $limit = 20, $end = '...') }}</div>
                                <div class="cell filter-cell">{{ str_limit($person->relationshiptypes->name, $limit = 15, $end = '...') }}</div>
                                <div class="cell">{{ str_limit($person->date_of_birth, $limit = 10, $end = '') }}</div>
                                <div class="cell actions">
                                    <a href="{{ route('persons.edit', $person->id) }}"><i class="fa fa-pencil"></i>Edit</a>
                                    <!--a href="{{ route('persons.destroy', $person->id) }}"><i class="fa fa-trash"></i>Delete</a-->
                                </div>
                            </div>
                        @endforeach
                    </div>
                @else
                    <p class="no-resource">You haven't added any persons yet, get started <a href="{{ route('persons.create') }}">here</a>.</p>                @endif
            @endif
        </div>
    </div>
@endsection